POST http://localhost/register HTTP/1.1
content-type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "pass",
    "confirm_password": "pass"
}

###

GET http://localhost/register HTTP/1.1

### Test Login

POST http://localhost/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "pass"
}