version: "3.3"
services:
  web:
    container_name: app
    build:
      context: ../
      dockerfile: Docker/Dockerfile.app
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ../
        target: /usr/src/app
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    networks:
      - backend
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend


networks:
  backend:
  frontend:
